# name of our workflow
name: Django CI/CD Workflow

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:  
  deploy:
    if: ${{ github.event_name == 'push' }} # will be fired if the trigger event is a push event.
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          KEY: ${{ secrets.SSHKEY }}
          script: >
            cd ${{ secrets.PROJECT_PATH }} 
            && git pull 
            && docker-compose -f backend/pruduction.yml up -d --build